### ISSUE TITLE
not recognize username and password in admin panel

### ISSUE THREAD

**Issue by salicius** [railwayapp-templates/django#9]
Hi, I'm using this template to test a django app on railway but in admin panel it doesn't recognize the username and password i digit (I'm using the postgres username and password set in the environment variable)

**Comment by ImLunaHey** [comment]
Related? https://github.com/railwayapp-templates/django/pull/4

**Comment by salicius** [comment]
Sorry not works it throws always the error 
"Please enter the correct username and password for a staff account. Note that both fields may be case-sensitive."
Seems like it doesn't see its env variables or am i wrong something?

**Comment by salicius** [comment]
Ok, i set a username and password via railway cli and now with that it works, i thought even with db credentials i could enter in the admin panel
